repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.11
  hooks:
    - id: ruff
      args:
        - --fix
    - id: ruff-format

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
    - id: mypy

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: no-commit-to-branch
